#!/bin/bash

set -e
set -x

NAME=`uuidgen`
BASE=/tmp/$NAME
ROOT=$BASE/rootfs-delta

MYIP="10.0.3.2"

mkdir -p $ROOT

cat <<EOF >$BASE/config
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.arch = x86_64

lxc.rootfs = overlayfs:/:$ROOT
lxc.utsname = $NAME

lxc.mount.auto = cgroup
lxc.aa_profile = lxc-container-default-with-nesting

lxc.mount.entry = /openchain openchain none bind 0 0
lxc.mount.entry = /opt/gopath/src/github.com/openblockchain/obc-peer opt/gopath/src/github.com/openblockchain/obc-peer none bind 0 0

lxc.network.type = veth
lxc.network.ipv4 = $MYIP
lxc.network.ipv4.gateway = auto
lxc.network.link = lxcbr0
lxc.network.flags = up
EOF

mkdir -p $ROOT/etc/init

#cat <<EOF >$ROOT/etc/init/console.conf
#exec /sbin/poweroff
#EOF

echo "`cat /etc/hostname`-$NAME" > $ROOT/etc/hostname

lxc-execute -f $BASE/config -n $NAME /openchain/obc-dev-env/scripts/cloneshell $MYIP

rm -rf $BASE
